// <auto-generated />
using System;
using Almond.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Almond.API.Migrations
{
    [DbContext(typeof(AlmondDbContext))]
    [Migration("20241106164349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Almond.API.Models.Bracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("Almond.API.Models.Bracket", b =>
                {
                    b.OwnsMany("Almond.API.Models.Participant", "Participants", b1 =>
                        {
                            b1.Property<int>("BracketId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("Guid")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Score")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BracketId", "Id");

                            b1.ToTable("Brackets");

                            b1.ToJson("Participants");

                            b1.WithOwner()
                                .HasForeignKey("BracketId");
                        });

                    b.OwnsMany("Almond.API.Models.Round", "Rounds", b1 =>
                        {
                            b1.Property<int>("BracketId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<bool>("Concluded")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Current")
                                .HasColumnType("boolean");

                            b1.HasKey("BracketId", "Id");

                            b1.ToTable("Brackets");

                            b1.ToJson("Rounds");

                            b1.WithOwner()
                                .HasForeignKey("BracketId");

                            b1.OwnsMany("Almond.API.Models.Match", "Matches", b2 =>
                                {
                                    b2.Property<int>("RoundBracketId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("RoundId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.HasKey("RoundBracketId", "RoundId", "Id");

                                    b2.ToTable("Brackets");

                                    b2.WithOwner()
                                        .HasForeignKey("RoundBracketId", "RoundId");

                                    b2.OwnsOne("Almond.API.Models.Participant", "Participant1", b3 =>
                                        {
                                            b3.Property<int>("MatchRoundBracketId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("MatchRoundId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("MatchId")
                                                .HasColumnType("integer");

                                            b3.Property<Guid>("Guid")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("Score")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("MatchRoundBracketId", "MatchRoundId", "MatchId");

                                            b3.ToTable("Brackets");

                                            b3.WithOwner()
                                                .HasForeignKey("MatchRoundBracketId", "MatchRoundId", "MatchId");
                                        });

                                    b2.OwnsOne("Almond.API.Models.Participant", "Participant2", b3 =>
                                        {
                                            b3.Property<int>("MatchRoundBracketId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("MatchRoundId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("MatchId")
                                                .HasColumnType("integer");

                                            b3.Property<Guid>("Guid")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("Score")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("MatchRoundBracketId", "MatchRoundId", "MatchId");

                                            b3.ToTable("Brackets");

                                            b3.WithOwner()
                                                .HasForeignKey("MatchRoundBracketId", "MatchRoundId", "MatchId");
                                        });

                                    b2.Navigation("Participant1");

                                    b2.Navigation("Participant2");
                                });

                            b1.Navigation("Matches");
                        });

                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
